name: CI/CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Bundle application
        run: npm run build

        
        
